Add training.py
Currently, training.py reaches up to preprocessing stage. After
this it fails with an import error
ImportError: cannot import name '_VF' from 'torch.nn'

Note, this was done with pytorch 1.5 cpu only from pip
I'll run it again with version 1.1, which is the latest version
in on the pytorch-rnn repository. Do not request a pull request
until this script runs successfully.

.gitignore ignores model directory which is made in training.py.
requirements.txt now has h5py required for torch-rnn.